# -*- coding: utf-8 -*-

"""
orca_step
A SEAMM plug-in for ORCA
"""

# Bring up the classes so that they appear to be directly in
# the orca_step package.
# The Substep base class is exposed at the package level so that substep
# modules (generated by the substep cookiecutter) can subclass it as
# `orca_step.Substep`.
from .orca_substep import Substep  # noqa: F401

from .orca import Orca  # noqa: F401, E501
from .orca_step import OrcaStep  # noqa: F401, E501
from .tk_orca import TkOrca  # noqa: F401, E501

from .metadata import metadata  # noqa: F401

# Handle versioneer
from ._version import get_versions

__author__ = "Paul Saxe"
__email__ = "psaxe@molssi.org"
versions = get_versions()
__version__ = versions["version"]
__git_revision__ = versions["full-revisionid"]
del get_versions, versions
